services:
  db:
    image: postgres:15
    container_name: moovie-db
    environment:
      POSTGRES_USER: moovie
      POSTGRES_PASSWORD: moovie123
      POSTGRES_DB: moovie_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/initdb:/docker-entrypoint-initdb.d

  db_test:
    image: postgres:15
    container_name: moovie-db-test
    environment:
      POSTGRES_USER: moovie_test
      POSTGRES_PASSWORD: moovie_test123
      POSTGRES_DB: moovie_test_db
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - ./server/initdb:/docker-entrypoint-initdb.d
    # No need to depend_on

  pgadmin:
    image: dpage/pgadmin4
    container_name: moovie-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moovie.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    build: ./server
    container_name: moovie-server
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      PGHOST: db
      PGPORT: 5432

volumes:
  db_data:
  pgadmin_data:
  db_test_data:
